controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


mail_send_test:
    path: /mail/send-test
    controller: App\Controller\MailController::sendTestEmail