controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail