<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV78QLEd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV78QLEd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV78QLEd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV78QLEd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV78QLEd\App_KernelDevDebugContainer([
    'container.build_hash' => 'V78QLEd',
    'container.build_id' => '79084374',
    'container.build_time' => 1678267486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV78QLEd');
