<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2mrxeb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2mrxeb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2mrxeb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2mrxeb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2mrxeb\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2mrxeb',
    'container.build_id' => '6a0df8d3',
    'container.build_time' => 1678266798,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2mrxeb');
